<?php

use Drupal\Core\Template\Attribute;

\Drupal::moduleHandler()->loadInclude('sis_overview', 'inc', 'preprocess');

/**
 * Implements hook_locale_translation_projects_alter().
 *
 * @param $projects
 *   List of all projects
 */
function sis_overview_locale_translation_projects_alter(&$projects) {
  $module_handler = \Drupal::service('module_handler');
  $path = $module_handler->getModule('sis_overview')->getPath();
  $projects['sis_overview']['info']['interface translation server pattern'] = $path . '/translations/%language.po';
}


function sis_overview_theme() {

  return [
    'term_overview' => [
      'variables' => ['term' => NULL, 'entities' => []],
    ],
    'term_overview_small' => [
      'variables' => ['term' => NULL, 'entities' => [], 'is_small' => FALSE],
    ],
    'overview_list_item' => [
      'variables' => ['headline' => NULL, 'link' => [], 'attributes' => []],
    ],
  ];
}

/**
 * @param $suggestions
 * @param array $variables
 */
function sis_overview_theme_suggestions_input_alter(&$suggestions, array $variables) {
  $element = $variables['element'];

  if (isset($element['#attributes']['data-twig-suggestion'])) {
    $suggestions[] = 'input__' . $element['#type'] . '__' . $element['#attributes']['data-twig-suggestion'];
  }
}

function sis_overview_preprocess_overview_list_item(&$variables) {
  $variables['attributes'] = new Attribute($variables['attributes']);
}

function sis_overview_entity_overview_count_options_alter(&$options, &$context) {
  $options = [
    4 => '4',
    6 => '6',
    8 => '8',
    9 => '9',
    12 => '12',
    15 => '15',
    16 => '16',
    18 => '18',
    20 => '20',
  ];
}
