<?php

use Drupal\Core\Database\Query\AlterableInterface;
use Drupal\Core\Render\Element;

\Drupal::moduleHandler()->loadInclude('sis_articles', 'inc', 'node.preprocess');
\Drupal::moduleHandler()->loadInclude('sis_articles', 'inc', 'user.preprocess');

function sis_articles_theme() {
  return [
    'list_element' => [
      'variables' => ['links' => [], 'article_type' => []],
    ],
    'factbox_items' => [
      'variables' => ['items' => []],
    ],
  ];
}

function sis_articles_preprocess_list_element(&$variables) {
  $fieldParent = $variables['article_type']->_referringItem->getParent()
    ->getParent()
    ->getEntity();

  if ($fieldParent->hasField('field_show_link_list') && $fieldParent->get('field_show_link_list')->value) {
    foreach (Element::children($variables['links']) as $key) {
      $variables['children'][] = $variables['links'][$key];
    }

    $variables['list_headline'] = $fieldParent->get('field_link_list_headline')->value;
    $variables['list_link_title'] = $fieldParent->get('field_link_list_title')->value;
  }
}

function sis_articles_query_sort_by_random_alter(AlterableInterface $query) {
  $query->orderRandom();
}

function sis_articles_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id === 'node_article_form') {

    if ($article_type = Drupal::requestStack()->getCurrentRequest()->get('type')) {
      if (!isset($form['field_article_type']['widget']['#options'])) {
        return;
      }
      foreach ($form['field_article_type']['widget']['#options'] as $key => $value) {
        if ($value === $article_type) {
          $form['field_article_type']['widget']['#default_value'] = $key;
        }
        else {
          unset($form['field_article_type']['widget']['#options'][$key]);
        }
      }
    }

    if (\Drupal::currentUser()->id() === 0 && isset($form['field_media_downloads']['#access'])) {
      $form['field_media_downloads']['#access'] = FALSE;
    }
  }

  else if ($form_id === 'views_form_media_library_page' || 'views_form_media_library_widget_document') {
    $form['#attached']['library'][] = 'sis/media-library';
  }

}
