<?php

\Drupal::moduleHandler()->loadInclude('sis_blog_post', 'inc', 'node.preprocess');
\Drupal::moduleHandler()->loadInclude('sis_blog_post', 'inc', 'block.preprocess');

/**
 * Implements hook_theme_suggestions_user_alter().
 *
 *   An array of alternate, more specific names for template files or theme
 *   functions.
 */
function sis_blog_post_theme_suggestions_user_alter(&$suggestions, $vars, $hook) {

  // Define the view mode.
  $mode = $vars['elements']['#view_mode'];

  // Create a theme hook suggestion which has the view mode name in it.
  $suggestions[] = 'user__' . $mode;
}
