<?php

use Drupal\Core\Link;

/**
 * Implements hook_preprocess().
 */
function sis_season_wheel_preprocess_block__inline_block__seasonal_wheel(array &$variables) {
  /** @var \Drupal\sis_season_wheel\Repository\SeasonWheelRepository $repository */
  $repository = \Drupal::service('sis_season_wheel.repository');
  $months = $repository->getMonthsTaxonomyKeyedByMachineName();
  $currentMonth = date('F');
  $currentMonthId = $months[strtolower($currentMonth)];

  $variables['#attached']['drupalSettings']['seasonal_wheel']['months'] = $months;
  $variables['#attached']['drupalSettings']['seasonal_wheel']['current_month'] = $currentMonthId;
  $variables['see_more'] = Link::createFromRoute(
    t('See all activities'),
    'entity.taxonomy_term.canonical',
    ['taxonomy_term' => $currentMonthId],
    ['attributes' => [
      'class' => 'seasonal-wheel__link js-seasonal-wheel__link'
    ]]
  );
  $variables['month_name'] = $currentMonth;
}
