<?php

\Drupal::moduleHandler()->loadInclude('sis_map', 'inc', 'block.preprocess');

function sis_map_theme() {
  return [
    'map' => [
      'variables' => [
        'markers' => [],
        'filters' => [],
        'icons' => [],
        'org_name' => NULL,
      ],
    ],
  ];
}

/**
 * @implements  hook_preprocess_HOOK
 *
 * @param $variables
 *
 * @throws \Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException
 * @throws \Drupal\Component\Plugin\Exception\PluginNotFoundException
 */
function sis_map_preprocess_map(&$variables) {
  $variables['#attached']['library'][] = 'sis_map/sis_map';

  if (isset($variables['markers'])) {
    $variables['#attached']['drupalSettings']['sis_map']['markers']
      = $variables['markers'];
  }
  if (isset($variables['filters'])) {
    $variables['#attached']['drupalSettings']['sis_map']['filters']
      = $variables['filters'];
  }
  if (isset($variables['icons'])) {
    $variables['#attached']['drupalSettings']['sis_map']['icons']
      = $variables['icons'];
  }
  $variables['button_text'] = atom_str('map-add-idea-button-text');
  $variables['button_link'] = atom_str('map-add-idea-button-link');
  $variables['map_title'] = atom_str('map-title');
  $variables['description_above_map'] = atom('map-description');
  if (Drupal::request()->get('uid')) {
    $variables['#attached']['drupalSettings']['sis_map']['render_all_markers_on_build'] = TRUE;
  }
  $variables['#attached']['drupalSettings']['sis_map']['display_map_helpers'] = Drupal::configFactory()->get('sis_map.settings')->get('display_map_helpers') ?? FALSE;
  $variables['max_visible_filters'] = Drupal::configFactory()->get('sis_map.settings')->get('max_visible_filters') ?? 5;
}
