#!/bin/bash
if [ -f ".env" ]; then
  if ! [ $(cat .env | grep "HASH_SALT") ]
  then
    read -p "Are you sure that you want to add new HASH_SALT to .env file (This can invalidate existing passwords) ? " -n 1 -r
    echo    # (optional) move to a new line
    if [[ $REPLY =~ ^[Yy]$ ]]
    then
    ln="HASH_SALT=\"$(openssl rand -base64 32)\""
    echo "$ln" >> .env
    fi
  fi
fi
