<?php

module_load_include('inc', 'sis_organization', 'form.alter');


/**
 * Implements hook_locale_translation_projects_alter().
 *
 * @param $projects
 *   List of all projects
 */
function sis_organization_locale_translation_projects_alter(&$projects) {
  $module_handler = \Drupal::service('module_handler');
  $path = $module_handler->getModule('sis_organization')->getPath();
  $projects['sis_organization']['info']['interface translation server pattern'] = $path . '/translations/%language.po';
}

function sis_organization_theme() {
  return [
    'page__organizations' => [
      'render element' => 'elements',
    ],
    'organization_overview' => [
      'variables' => ['term' => NULL, 'entities' => []]
    ],
    'organization_content_slideshow' => [
      'render element' => 'elements',
    ]
  ];
}

function sis_organization_preprocess_page__organizations(&$variables) {
  /** @var \Drupal\sis_organization\Services\OrganizationContentDeliveryService $contentDelivery */
  $contentDelivery = \Drupal::service('sis_organization.content_delivery');
  $variables['page']['content_slideshow'] = $contentDelivery->getRandomArticlesFromOrganization();

  $block_manager = \Drupal::service('plugin.manager.block');

  // You can hard code configuration or you load from settings.
  $config = [];
  $plugin_block = $block_manager->createInstance('premium_breadcrumb_block', $config);
  $breadcrumb = $plugin_block->build();

  // Add the cache tags/contexts.
  \Drupal::service('renderer')->addCacheableDependency($breadcrumb, $plugin_block);
  $variables['breadcrumb'] = $breadcrumb;
}

function sis_organization_preprocess_profile__full(&$variables) {
  $block_manager = \Drupal::service('plugin.manager.block');

  // You can hard code configuration or you load from settings.
  $config = [];
  $plugin_block = $block_manager->createInstance('premium_breadcrumb_block', $config);
  $breadcrumb = $plugin_block->build();

  // Add the cache tags/contexts.
  \Drupal::service('renderer')->addCacheableDependency($breadcrumb, $plugin_block);
  return $variables['breadcrumb'] = $breadcrumb;
}
