<?php

use Drupal\Core\Render\Element;

/**
 * Implements hook_locale_translation_projects_alter().
 *
 * @param $projects
 *   List of all projects
 */
function sis_lexicon_locale_translation_projects_alter(&$projects) {
  $module_handler = \Drupal::service('module_handler');
  $path = $module_handler->getModule('sis_lexicon')->getPath();
  $projects['sis_lexicon']['info']['interface translation server pattern'] = $path . '/translations/%language.po';
}
